# * GENERAL OPTIONS

[options]
HoldPkg = pacman glibc
Architecture = auto

# NOTE: Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
# IgnorePkg   =
# IgnoreGroup =

# * Misc options

Color
CheckSpace
ParallelDownloads = 10
DownloadUser = alpm
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

# * REPOSITORIES

# NOTE: Repository entries are of the format:
# [repo-name]
# Server = ServerName
# Include = IncludePath

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
